import '@/index.css';

import { M_PLUS_1p, Noto_Sans_JP } from 'next/font/google';
import { HomeAppBar } from './Appbar';
import { Suspense } from 'react';
import Provider from './Provider';
import Loading from './dashboard/loading';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const mplus1p = M_PLUS_1p({ weight: ['400', '700', '900'], variable: '--font-mplus1p', subsets: ['latin'] });
const notoSansJp = Noto_Sans_JP({ variable: '--font-notoSansJp', subsets: ['latin'] });

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <head/>
      <body>
        <Provider>
          <HomeAppBar />
          {children}
        </Provider>
      </body>
    </html>
  );
}