import '@/index.css';
import { SessionProvider, useSession } from 'next-auth/react'

import { M_PLUS_1p, Noto_Sans_JP } from 'next/font/google';
import { MuiStyledEngineProvider, MuiThemeProvider, NextAuthSessionProvider } from './Provider';
import { Session, getServerSession } from 'next-auth';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const mplus1p = M_PLUS_1p({ weight: ['400', '700', '900'], variable: '--font-mplus1p', subsets: ['latin'] });
const notoSansJp = Noto_Sans_JP({ variable: '--font-notoSansJp', subsets: ['latin'] });

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <head/>
      <body>
        <NextAuthSessionProvider>
          <MuiStyledEngineProvider>
            <MuiThemeProvider>
              {children}
            </MuiThemeProvider>
          </MuiStyledEngineProvider>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}